let suggestions = [
    "channel",
    "codingLab",
    "codingnepal",
    "youtub",
    "youtuber",
    "youtub channel",
    "blogger",
    "bollywood",
    "vlogger",
    "vechiles",
    "facebook",
    "freelancer",
    "facebook page",
    "developer",
    "web desiner",
    "Login Form in Html & CSS",
    "How to learn HTML & CSS",
    "How to learn javascript",
    "how to become freelancer",
    "how to become web desinger",
    "how to start gaming channel",
    "how to start youtube channel",
    "what does html stands for ?",
    "what does css stands for",
]